objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <description>Store information about the feature releases</description>
    <label>Release</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Release Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Release__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Stores the country</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Release__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Stores the description</description>
    <label>Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Release__c/fields/External_Link__c.field-meta.xml
<CustomField>
    <fullName>External_Link__c</fullName>
    <description>Store the link of external website</description>
    <label>External Link</label>
    <type>Url</type>
</CustomField>

objects/Release__c/fields/Profiles__c.field-meta.xml
<CustomField>
    <fullName>Profiles__c</fullName>
    <description>Stores the profiles</description>
    <label>Profiles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard User</fullName>
            </value>
            <value>
                <fullName>Marketing User</fullName>
            </value>
            <value>
                <fullName>Custom: Sales Profile</fullName>
            </value>
            <value>
                <fullName>Custom: Support Profile</fullName>
            </value>
            <value>
                <fullName>Custom: Marketing Profile</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Solution Manager</fullName>
            </value>
            <value>
                <fullName>Standard Platform User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Release__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <description>Store the date of the release</description>
    <label>Release Date</label>
    <type>Date</type>
</CustomField>

objects/Release__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Stores the title of releases records</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/ReleaseUpdateController.cls
public with sharing class ReleaseUpdateController {
    

    @AuraEnabled(cacheable=true)
    public static List<Release__c> getRelease(){
        // Map<Id,Release__c> releaseMap = new Map<Id,Release__c>();
        // for(Release__c rel : [SELECT Id, Name, Country__c, Description__c, Profiles__c,Release_Date__c,Title__c,External_Link__c FROM Release__c]){
        //     releaseMap.put(rel.Id,rel);
        // }

        // Map<Id, Map<Id, String>> relatedFileMap = getRelatedFiles(releaseMap.keySet());
        // Map<Release__c,Map<Id,String>> finalMap = new Map<Release__c,Map<Id,String>>();
        // for (Id recId : releaseMap.keySet()) {
        //     if(relatedFileMap.containsKey(recId)){
        //         finalMap.put(releaseMap.get(recId),relatedFileMap.get(recId));
        //     }
        //     else {
        //         finalMap.put(releaseMap.get(recId),new Map<Id,String>());
        //     }
        // }       
        // return finalMap;

        return [SELECT Id, Name, Country__c, Description__c, Profiles__c,Release_Date__c,Title__c,External_Link__c,(SELECT ContentDocumentId,ContentDocument.Title  FROM ContentDocumentLinks) FROM Release__c ];
    }


    public static Map<Id, Map<Id, String>> getRelatedFiles(Set<Id> recordIds){
        try {
            //Set<Id> recordIds = getRelease().keySet();
            Map<Id,Id> recordIdToContentIdMap = new Map<Id,Id>();
            List<ContentDocumentLink> files = [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN :recordIds];
            List<Id> fileIds = new List<Id>();
            for(ContentDocumentLink doc : files){
                fileIds.add(doc.ContentDocumentId);
                recordIdToContentIdMap.put(doc.ContentDocumentId,doc.LinkedEntityId);
                
            }
            Map<Id,String> contentToNameMap = new Map<Id,String>();
            List<ContentVersion> docs = [SELECT ContentDocumentId ,FileExtension,Title FROM ContentVersion WHERE ContentDocumentId IN : fileIds];
            for(ContentVersion docLink : docs){

                contentToNameMap.put(docLink.ContentDocumentId,docLink.Title);
            }

            Map<Id, Map<Id, String>> resultMap = new  Map<Id, Map<Id, String>>();
            for (Id conId : recordIdToContentIdMap.keySet()){
                Id recordId = recordIdToContentIdMap.get(conId);
                String filename = contentToNameMap.get(conId);
                if(!resultMap.containsKey(recordId)){
                    resultMap.put(recordId, new Map<Id, String>());
                }
                resultMap.get(recordId).put(conId, filename);
            }
            return resultMap; 
        }

        catch (Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }
}